version: "3"
services:
  django:
    build: ./django
    volumes:
      - ./django:/django
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: sh -c "sleep 1 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
    volumes:
      - psql-db:/var/lib/postgresql/data
  
volumes:
  psql-db: