version: "3"
services:
  django:
    build: ./django
    env_file:
      - ./.env
    volumes:
      - ./django:/django
    command: sh -c "sleep 1 && python manage.py migrate && uwsgi --socket :8001 --module line_bot.wsgi"
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env
    volumes:
      - psql-db:/var/lib/postgresql/data

  nginx:
    image: nginx:1.17.8
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      #- ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./django/static:/static
    ports:
      - "8000:8000"
    depends_on:
      - django
      - db
  
volumes:
  psql-db: