# Generated by Django 3.0.3 on 2020-02-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserIdModel',
        ),
    ]
